/* Bean & Bloom blog seed — 50 posts */
(function (root) {
  var blogs = [
  {
    "id": "blog-pour-over-ritual-at-home",
    "slug": "pour-over-ritual-at-home",
    "title": "The pour-over ritual: slower coffee, clearer flavor",
    "excerpt": "A calm, repeatable pour-over method that unlocks sweetness without cafe equipment.",
    "category": "Brew guides",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-02T10:00:00.000Z",
    "content": "A calm, repeatable pour-over method that unlocks sweetness without cafe equipment.\n\n## Why it matters\nThe pour-over ritual: slower coffee, clearer flavor is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our brew guides desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-dialing-in-home-espresso",
    "slug": "dialing-in-home-espresso",
    "title": "Dialing in espresso without the guesswork",
    "excerpt": "A practical checklist for dose, yield, and time — so home shots taste intentional.",
    "category": "Espresso",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-03T10:00:00.000Z",
    "content": "A practical checklist for dose, yield, and time — so home shots taste intentional.\n\n## Why it matters\nDialing in espresso without the guesswork is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-how-to-store-coffee-beans",
    "slug": "how-to-store-coffee-beans",
    "title": "How to store coffee beans so they stay vivid",
    "excerpt": "Skip the fridge myths. Protect aroma with airtight, cool, and dark habits.",
    "category": "Care",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-04T10:00:00.000Z",
    "content": "Skip the fridge myths. Protect aroma with airtight, cool, and dark habits.\n\n## Why it matters\nHow to store coffee beans so they stay vivid is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our care desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-building-a-coffee-gift-box",
    "slug": "building-a-coffee-gift-box",
    "title": "Building a coffee gift box that feels personal",
    "excerpt": "Pair a bag, a mug, and a short brew note — gifts that get used, not shelved.",
    "category": "Gifting",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-05T10:00:00.000Z",
    "content": "Pair a bag, a mug, and a short brew note — gifts that get used, not shelved.\n\n## Why it matters\nBuilding a coffee gift box that feels personal is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gifting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-french-press-for-weeknights",
    "slug": "french-press-for-weeknights",
    "title": "French press for busy weeknights",
    "excerpt": "A forgiving immersion brew when you want body without babysitting the kettle.",
    "category": "Brew guides",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-06T10:00:00.000Z",
    "content": "A forgiving immersion brew when you want body without babysitting the kettle.\n\n## Why it matters\nFrench press for busy weeknights is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our brew guides desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-water-quality-and-flavor",
    "slug": "water-quality-and-flavor",
    "title": "Why water quality changes everything in the cup",
    "excerpt": "Minerals, hardness, and filters — the quiet variables behind bright or dull coffee.",
    "category": "Care",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": true,
    "published": true,
    "publishedAt": "2026-01-07T10:00:00.000Z",
    "content": "Minerals, hardness, and filters — the quiet variables behind bright or dull coffee.\n\n## Why it matters\nWhy water quality changes everything in the cup is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our care desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-milk-steaming-basics",
    "slug": "milk-steaming-basics",
    "title": "Milk steaming basics for home baristas",
    "excerpt": "Texture, temperature, and timing for silky microfoam without a cafe wand.",
    "category": "Espresso",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-08T10:00:00.000Z",
    "content": "Texture, temperature, and timing for silky microfoam without a cafe wand.\n\n## Why it matters\nMilk steaming basics for home baristas is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-single-origin-vs-blend",
    "slug": "single-origin-vs-blend",
    "title": "Single origin vs blend: choosing with intention",
    "excerpt": "When to chase terroir and when a house blend is the smarter daily driver.",
    "category": "Roasting",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-09T10:00:00.000Z",
    "content": "When to chase terroir and when a house blend is the smarter daily driver.\n\n## Why it matters\nSingle origin vs blend: choosing with intention is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-cold-brew-concentrate-guide",
    "slug": "cold-brew-concentrate-guide",
    "title": "Cold brew concentrate you will actually finish",
    "excerpt": "Ratios, steep times, and dilution tips for fridge-ready bottles.",
    "category": "Recipes",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-10T10:00:00.000Z",
    "content": "Ratios, steep times, and dilution tips for fridge-ready bottles.\n\n## Why it matters\nCold brew concentrate you will actually finish is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-grinder-burr-care",
    "slug": "grinder-burr-care",
    "title": "Keeping your grinder sharp and clean",
    "excerpt": "Simple maintenance that protects flavor clarity and motor life.",
    "category": "Gear",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-11T10:00:00.000Z",
    "content": "Simple maintenance that protects flavor clarity and motor life.\n\n## Why it matters\nKeeping your grinder sharp and clean is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-weekend-brunch-coffee-menu",
    "slug": "weekend-brunch-coffee-menu",
    "title": "A weekend brunch coffee menu at home",
    "excerpt": "Pair mellow blends with pastries and a ceramic mug ritual.",
    "category": "Seasonal",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-12T10:00:00.000Z",
    "content": "Pair mellow blends with pastries and a ceramic mug ritual.\n\n## Why it matters\nA weekend brunch coffee menu at home is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our seasonal desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-latte-art-starter-shapes",
    "slug": "latte-art-starter-shapes",
    "title": "Latte art starter shapes that build confidence",
    "excerpt": "Hearts and tulips — practice patterns that teach flow control.",
    "category": "Espresso",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-13T10:00:00.000Z",
    "content": "Hearts and tulips — practice patterns that teach flow control.\n\n## Why it matters\nLatte art starter shapes that build confidence is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-decaf-without-compromise",
    "slug": "decaf-without-compromise",
    "title": "Decaf without compromise",
    "excerpt": "Swiss Water and sugarcane process notes for evening cups that still taste like coffee.",
    "category": "Roasting",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-14T10:00:00.000Z",
    "content": "Swiss Water and sugarcane process notes for evening cups that still taste like coffee.\n\n## Why it matters\nDecaf without compromise is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-travel-brew-kit",
    "slug": "travel-brew-kit",
    "title": "Packing a travel brew kit that stays light",
    "excerpt": "AeroPress, hand grinder, and scales that fit a weekend bag.",
    "category": "Gear",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-15T10:00:00.000Z",
    "content": "AeroPress, hand grinder, and scales that fit a weekend bag.\n\n## Why it matters\nPacking a travel brew kit that stays light is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-tasting-notes-decoded",
    "slug": "tasting-notes-decoded",
    "title": "Tasting notes decoded for shoppers",
    "excerpt": "What floral, chocolate, and citrus really mean on a bag label.",
    "category": "Cafe culture",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-16T10:00:00.000Z",
    "content": "What floral, chocolate, and citrus really mean on a bag label.\n\n## Why it matters\nTasting notes decoded for shoppers is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-aeropress-inverted-method",
    "slug": "aeropress-inverted-method",
    "title": "AeroPress inverted method, explained",
    "excerpt": "A controlled immersion style for cleaner sweetness and less grit.",
    "category": "Brew guides",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-17T10:00:00.000Z",
    "content": "A controlled immersion style for cleaner sweetness and less grit.\n\n## Why it matters\nAeroPress inverted method, explained is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our brew guides desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-seasonal-ethiopia-lots",
    "slug": "seasonal-ethiopia-lots",
    "title": "How we taste seasonal Ethiopia lots",
    "excerpt": "Cupping tables, score sheets, and why jasmine notes come and go.",
    "category": "Roasting",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-18T10:00:00.000Z",
    "content": "Cupping tables, score sheets, and why jasmine notes come and go.\n\n## Why it matters\nHow we taste seasonal Ethiopia lots is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-office-coffee-upgrade",
    "slug": "office-coffee-upgrade",
    "title": "Upgrade the office coffee corner",
    "excerpt": "Pods, drip, and etiquette for shared brew stations that stay tidy.",
    "category": "Cafe culture",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-19T10:00:00.000Z",
    "content": "Pods, drip, and etiquette for shared brew stations that stay tidy.\n\n## Why it matters\nUpgrade the office coffee corner is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-mocha-at-home",
    "slug": "mocha-at-home",
    "title": "Building a better mocha at home",
    "excerpt": "Chocolate, espresso, and milk ratios that avoid syrupy heaviness.",
    "category": "Recipes",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-20T10:00:00.000Z",
    "content": "Chocolate, espresso, and milk ratios that avoid syrupy heaviness.\n\n## Why it matters\nBuilding a better mocha at home is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-filter-paper-rinse",
    "slug": "filter-paper-rinse",
    "title": "Why rinsing filter paper matters",
    "excerpt": "Paper taste, preheat, and the 10-second habit that cleans up cups.",
    "category": "Brew guides",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-21T10:00:00.000Z",
    "content": "Paper taste, preheat, and the 10-second habit that cleans up cups.\n\n## Why it matters\nWhy rinsing filter paper matters is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our brew guides desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-gift-guide-under-1500",
    "slug": "gift-guide-under-1500",
    "title": "Coffee gift guide under ₹1,500",
    "excerpt": "Thoughtful picks — mugs, bags, and tools that feel premium without excess.",
    "category": "Gifting",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-22T10:00:00.000Z",
    "content": "Thoughtful picks — mugs, bags, and tools that feel premium without excess.\n\n## Why it matters\nCoffee gift guide under ₹1,500 is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gifting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-espresso-channeling-fixes",
    "slug": "espresso-channeling-fixes",
    "title": "Fixing espresso channeling fast",
    "excerpt": "Distribution, WDT, and tamp habits that stop uneven extraction.",
    "category": "Espresso",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-23T10:00:00.000Z",
    "content": "Distribution, WDT, and tamp habits that stop uneven extraction.\n\n## Why it matters\nFixing espresso channeling fast is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-monsoon-malabar-story",
    "slug": "monsoon-malabar-story",
    "title": "The story behind Monsoon Malabar",
    "excerpt": "How monsoon processing shapes body, spice, and low-acid comfort.",
    "category": "Roasting",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-24T10:00:00.000Z",
    "content": "How monsoon processing shapes body, spice, and low-acid comfort.\n\n## Why it matters\nThe story behind Monsoon Malabar is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-iced-americano-ritual",
    "slug": "iced-americano-ritual",
    "title": "The iced Americano ritual",
    "excerpt": "Long black style dilution, ice, and citrus optional twists.",
    "category": "Recipes",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-25T10:00:00.000Z",
    "content": "Long black style dilution, ice, and citrus optional twists.\n\n## Why it matters\nThe iced Americano ritual is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-scale-habits",
    "slug": "scale-habits",
    "title": "Brew scale habits worth keeping",
    "excerpt": "Tare, timers, and logging recipes so good cups become repeatable.",
    "category": "Gear",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-26T10:00:00.000Z",
    "content": "Tare, timers, and logging recipes so good cups become repeatable.\n\n## Why it matters\nBrew scale habits worth keeping is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-sunday-slow-brew",
    "slug": "sunday-slow-brew",
    "title": "Sunday slow brew: a two-hour cafe at home",
    "excerpt": "Playlist, pour-over, and pastry — making space for unhurried coffee.",
    "category": "Seasonal",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-27T10:00:00.000Z",
    "content": "Playlist, pour-over, and pastry — making space for unhurried coffee.\n\n## Why it matters\nSunday slow brew: a two-hour cafe at home is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our seasonal desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-cleaning-espresso-machines",
    "slug": "cleaning-espresso-machines",
    "title": "Cleaning home espresso machines",
    "excerpt": "Backflush, steam wand wipe-downs, and descaling cadence.",
    "category": "Care",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-28T10:00:00.000Z",
    "content": "Backflush, steam wand wipe-downs, and descaling cadence.\n\n## Why it matters\nCleaning home espresso machines is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our care desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-pairing-pastries",
    "slug": "pairing-pastries",
    "title": "Pairing pastries with roast profiles",
    "excerpt": "Croissants with brunch blends, biscotti with dark cocoa.",
    "category": "Recipes",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-29T10:00:00.000Z",
    "content": "Croissants with brunch blends, biscotti with dark cocoa.\n\n## Why it matters\nPairing pastries with roast profiles is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-v60-bloom-timing",
    "slug": "v60-bloom-timing",
    "title": "V60 bloom timing that unlocks sweetness",
    "excerpt": "Gas release, pulse pours, and how grind interacts with bloom.",
    "category": "Brew guides",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-30T10:00:00.000Z",
    "content": "Gas release, pulse pours, and how grind interacts with bloom.\n\n## Why it matters\nV60 bloom timing that unlocks sweetness is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our brew guides desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-coffee-journal-habit",
    "slug": "coffee-journal-habit",
    "title": "Keeping a coffee journal that helps",
    "excerpt": "What to write down — and what to ignore — after each brew.",
    "category": "Cafe culture",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-01-31T10:00:00.000Z",
    "content": "What to write down — and what to ignore — after each brew.\n\n## Why it matters\nKeeping a coffee journal that helps is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-capsule-vs-fresh",
    "slug": "capsule-vs-fresh",
    "title": "Capsules vs fresh beans: an honest comparison",
    "excerpt": "Convenience, waste, and when pods still make sense.",
    "category": "Gear",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-01T10:00:00.000Z",
    "content": "Convenience, waste, and when pods still make sense.\n\n## Why it matters\nCapsules vs fresh beans: an honest comparison is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-chai-and-coffee-crossover",
    "slug": "chai-and-coffee-crossover",
    "title": "Chai and coffee crossover drinks",
    "excerpt": "Masala spice meets espresso for monsoon evenings.",
    "category": "Recipes",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-02T10:00:00.000Z",
    "content": "Masala spice meets espresso for monsoon evenings.\n\n## Why it matters\nChai and coffee crossover drinks is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-roast-date-matters",
    "slug": "roast-date-matters",
    "title": "Why roast date matters more than roast level",
    "excerpt": "Freshness windows for espresso vs filter.",
    "category": "Care",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-03T10:00:00.000Z",
    "content": "Freshness windows for espresso vs filter.\n\n## Why it matters\nWhy roast date matters more than roast level is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our care desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-hosting-cupping",
    "slug": "hosting-cupping",
    "title": "Hosting a home cupping for friends",
    "excerpt": "Spoons, bowls, and a no-jargon tasting sheet.",
    "category": "Cafe culture",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-04T10:00:00.000Z",
    "content": "Spoons, bowls, and a no-jargon tasting sheet.\n\n## Why it matters\nHosting a home cupping for friends is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-nitro-style-cold-brew",
    "slug": "nitro-style-cold-brew",
    "title": "Nitro-style cold brew without nitrogen kits",
    "excerpt": "Frothers, cans, and mouthfeel tricks for creamy cold cups.",
    "category": "Recipes",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-05T10:00:00.000Z",
    "content": "Frothers, cans, and mouthfeel tricks for creamy cold cups.\n\n## Why it matters\nNitro-style cold brew without nitrogen kits is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-choosing-a-kettle",
    "slug": "choosing-a-kettle",
    "title": "Choosing a gooseneck kettle",
    "excerpt": "Flow rate, temperature hold, and stovetop vs electric.",
    "category": "Gear",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-06T10:00:00.000Z",
    "content": "Flow rate, temperature hold, and stovetop vs electric.\n\n## Why it matters\nChoosing a gooseneck kettle is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-holiday-gift-boxes",
    "slug": "holiday-gift-boxes",
    "title": "Holiday gift boxes that feel considered",
    "excerpt": "Bundles with brew cards and tasting notes for December.",
    "category": "Gifting",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-07T10:00:00.000Z",
    "content": "Bundles with brew cards and tasting notes for December.\n\n## Why it matters\nHoliday gift boxes that feel considered is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gifting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-espresso-for-milk-drinks",
    "slug": "espresso-for-milk-drinks",
    "title": "Espresso recipes that hold up in milk",
    "excerpt": "Slightly longer ratios for flat whites and cappuccinos.",
    "category": "Espresso",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-08T10:00:00.000Z",
    "content": "Slightly longer ratios for flat whites and cappuccinos.\n\n## Why it matters\nEspresso recipes that hold up in milk is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-sustainable-packaging",
    "slug": "sustainable-packaging",
    "title": "How we think about packaging",
    "excerpt": "Valves, recyclability, and protecting aroma in transit.",
    "category": "Cafe culture",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-09T10:00:00.000Z",
    "content": "Valves, recyclability, and protecting aroma in transit.\n\n## Why it matters\nHow we think about packaging is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-morning-routine-15-min",
    "slug": "morning-routine-15-min",
    "title": "A 15-minute morning coffee routine",
    "excerpt": "From grind to sip without rushing the bloom.",
    "category": "Home brew",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-10T10:00:00.000Z",
    "content": "From grind to sip without rushing the bloom.\n\n## Why it matters\nA 15-minute morning coffee routine is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our home brew desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-filter-vs-espresso-beans",
    "slug": "filter-vs-espresso-beans",
    "title": "Filter beans on espresso (and vice versa)",
    "excerpt": "When to experiment and when to stick to the dial-in blend.",
    "category": "Roasting",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-11T10:00:00.000Z",
    "content": "When to experiment and when to stick to the dial-in blend.\n\n## Why it matters\nFilter beans on espresso (and vice versa) is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-biscuits-and-brew",
    "slug": "biscuits-and-brew",
    "title": "Biscotti, cookies, and dunkable brew pairings",
    "excerpt": "Textures that complement body and bitterness.",
    "category": "Recipes",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-12T10:00:00.000Z",
    "content": "Textures that complement body and bitterness.\n\n## Why it matters\nBiscotti, cookies, and dunkable brew pairings is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our recipes desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-whats-in-a-blend",
    "slug": "whats-in-a-blend",
    "title": "What is really in a house blend",
    "excerpt": "Origins, roast curves, and consistency goals.",
    "category": "Roasting",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-13T10:00:00.000Z",
    "content": "Origins, roast curves, and consistency goals.\n\n## Why it matters\nWhat is really in a house blend is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our roasting desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-steam-wand-texture",
    "slug": "steam-wand-texture",
    "title": "Reading milk texture by ear and eye",
    "excerpt": "Whistle, sheen, and the stop temperature that saves drinks.",
    "category": "Espresso",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-14T10:00:00.000Z",
    "content": "Whistle, sheen, and the stop temperature that saves drinks.\n\n## Why it matters\nReading milk texture by ear and eye is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our espresso desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-apartment-friendly-gear",
    "slug": "apartment-friendly-gear",
    "title": "Apartment-friendly brew gear",
    "excerpt": "Quiet grinders, small footprints, and renter-safe setups.",
    "category": "Gear",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-15T10:00:00.000Z",
    "content": "Quiet grinders, small footprints, and renter-safe setups.\n\n## Why it matters\nApartment-friendly brew gear is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-rainy-day-coffee",
    "slug": "rainy-day-coffee",
    "title": "Rainy-day coffee drinks we love",
    "excerpt": "Spiced lattes, cocoa mocha, and slow french press.",
    "category": "Seasonal",
    "author": "Bean & Bloom",
    "coverImage": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-16T10:00:00.000Z",
    "content": "Spiced lattes, cocoa mocha, and slow french press.\n\n## Why it matters\nRainy-day coffee drinks we love is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our seasonal desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-reading-altitude",
    "slug": "reading-altitude",
    "title": "Reading altitude on coffee bags",
    "excerpt": "How elevation hints at density and brewing adjustments.",
    "category": "Cafe culture",
    "author": "Roast desk",
    "coverImage": "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-17T10:00:00.000Z",
    "content": "How elevation hints at density and brewing adjustments.\n\n## Why it matters\nReading altitude on coffee bags is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-reheating-coffee",
    "slug": "reheating-coffee",
    "title": "Should you reheat coffee?",
    "excerpt": "Better habits than the microwave — and when to start fresh.",
    "category": "Care",
    "author": "Studio",
    "coverImage": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-18T10:00:00.000Z",
    "content": "Better habits than the microwave — and when to start fresh.\n\n## Why it matters\nShould you reheat coffee? is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our care desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-first-espresso-machine",
    "slug": "first-espresso-machine",
    "title": "Buying your first espresso machine",
    "excerpt": "Budgets, boilers, and features that matter for home.",
    "category": "Gear",
    "author": "Brew lab",
    "coverImage": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-19T10:00:00.000Z",
    "content": "Budgets, boilers, and features that matter for home.\n\n## Why it matters\nBuying your first espresso machine is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our gear desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  },
  {
    "id": "blog-closing-the-cafe-day",
    "slug": "closing-the-cafe-day",
    "title": "Closing rituals from our roast desk",
    "excerpt": "Cleaning, notes, and setting up tomorrow’s first brew.",
    "category": "Cafe culture",
    "author": "Taste panel",
    "coverImage": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1600&q=80",
    "featured": false,
    "published": true,
    "publishedAt": "2026-02-20T10:00:00.000Z",
    "content": "Cleaning, notes, and setting up tomorrow’s first brew.\n\n## Why it matters\nClosing rituals from our roast desk is one of those small practices that compounds. A little more attention at the kettle, the grinder, or the cupping table shows up as clearer sweetness and fewer wasted bags.\n\n## Try this at home\n1. Start with fresh beans and a clean brewer.\n2. Change one variable at a time — grind, dose, or water temperature.\n3. Write a two-line note about aroma and finish.\n4. Repeat the same recipe tomorrow before you chase a new one.\n\n## From our cafe culture desk\nWe roast and pack for home rituals, not theater. Shop the collection when you are ready to put the guide into a cup — and message us on WhatsApp if you want a grind or gear recommendation tailored to your setup.\n\nBean & Bloom — roasted with care, shipped with care."
  }
];
  if (typeof module === 'object' && module.exports) {
    module.exports = blogs;
  }
  root.BEAN_BLOOM_DEFAULT_BLOGS = blogs;
})(typeof globalThis !== 'undefined' ? globalThis : this);
